### ISSUE TITLE
Line/column number tracking and custom errors

### ISSUE THREAD

**Issue by ethindp** [Hejsil/mecha#54] opened 2023-09-16 21:24 UTC
It would be nice if line/column tracking was done automatically. Also it's difficult to see how to do custom errors.... I'm unsure how this would be implemented though.

**Comment by Hejsil** [comment] 2023-09-17 10:13
This is a duplicate of https://github.com/Hejsil/mecha/issues/41

**Closed by Hejsil** 2023-09-17 10:13 UTC

**Comment by joelreymont** [comment] 2024-11-07 06:52
See PR #76.
